### DISCUSSION TITLE
Anyone knows where do I set this thing PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True?

### DISCUSSION THREAD

**Discussion by dilectiogames** [lllyasviel/FramePack#438] [Q&A]
So it works like one hour calculates the entire blue bar till it gets to 25 then gives this errors about

_"torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 544.00 MiB. GPU 0 has a total capacity of 6.00 GiB of which 0 bytes is free. Of the allocated memory 3.59 GiB is allocated by PyTorch, and 1.60 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management"_

so 1.6 is higher that 544 so maybe I can fix it IF I WOULD KNOW WHERE TO ADD THIS THING

searching online I get answer: you just set this bro!

┻━┻ ︵╰(°□°╰)

where?!

thank you for your help

**Comment by dilectiogames** [comment]
so I've added this to windows enviroment variables. by setting PYTORCH_CUDA_ALLOC_CONF as variable name and expandable_segments:True as variable value.

I think that is the place to add it because now when starting framepack it gives me this error

_UserWarning: expandable_segments not supported on this platform (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\c10/cuda/CUDAAllocatorConfig.h:28.)
  return torch.nn.Parameter(p.to(**kwargs), requires_grad=p.requires_grad)_

what to do bros??

**Comment by Faishun** [comment]
Don't. Set page file virtual memory to 50 GB from your system drive. Google how to increase virtual memory = issue gone

**Reply by dilectiogames** [reply]
it set to system managed at the moment. Isn't this something that will give it enough it needs? 50Gb - 100Gb, whatever it needs?

**Comment by atf130** [comment]
has anyone got this fixed at all, I have same error, increased virtual memory same error?
