### DISCUSSION TITLE
1080 ti not possible?

### DISCUSSION THREAD

**Discussion by af1kfb** [lllyasviel/FramePack#529] [Q&A]
I have a 1080ti. My video card is really a lot better than say a RTX 3060 but it does not seem to be compatible with this at all. Just keep getting the "out of memory" error every time I try to create anything. Upped the system VRAM to 64GB but still same error. Also changed environment variable as error message suggests. Anyone been able to get this to work with a 1080ti?

**Comment by af1kfb** [comment]
i used the NV20 fork to fix this and it works now if anyone wants to try it.

**Comment by EKI-INDRADI** [comment]
GTX 1080 Ti (6.1) is fully supported by CUDA 11.8 (CMIW because information from AI)

im use RTX 3060 12 GB & RTX 3080 10GB running well with cuda 118 or 12X

running with spesific cuda devices  1 or 0 (if you have multiple gpu), (gpu index start with 0,1,2,3, etc . . ), makesure gpu index from
```sh
nvidia-smi
```

memory.py

```python
import torch


cpu = torch.device('cpu')
# gpu = torch.device(f'cuda:{torch.cuda.current_device()}')
#---- SPESIFIC CUDA
# torch.cuda.set_device(1)
torch.cuda.set_device(0)
gpu = torch.device(f'cuda:{torch.cuda.current_device()}')
#---- SPESIFIC CUDA
gpu_complete_modules = []

```


how install https://github.com/lllyasviel/FramePack/discussions/582 with xformers cuda 118 improve performance 130% better than use cuda 12x , because xformers not supported new version cuda

and  start

```sh
conda activate framepack
python demo_gradio_f1.py

```
