### ISSUE TITLE
启动时静默报错

### ISSUE THREAD

**Issue by GaoDaaxiong** [lllyasviel/FramePack#107]
![Image](https://github.com/user-attachments/assets/471ba8a5-8c4f-480b-8617-6f0e0b025dd3)
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
Namespace(share=False, server='127.0.0.1', port=None, inbrowser=True)
Free VRAM 6.890625 GB
High-VRAM Mode: False
Downloading shards: 100%|████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 10.41it/s]
Fetching 3 files: 100%|██████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:00<?, ?it/s] 请按任意键继续. . .

运行windows一键安装包，到这一步就静默退出
看了一下代码到这一部卡住了
transformer = HunyuanVideoTransformer3DModelPacked.from_pretrained('lllyasviel/FramePackI2V_HY', torch_dtype=torch.bfloat16).cpu()
模型已经都下载下来了，是因为电脑显存不足吗

**Comment by nitinmukesh** [comment]
Increase virtual memory

**Comment by xyshyniaphy** [comment]
我64g内存，之前把虚拟内存关了，也是同样的地方突然退出。
然后，把虚拟内存设成8G，重启，就正常运行了

**Comment by SoiTeoh** [comment]
> 我64g内存，之前把虚拟内存关了，也是同样的地方突然退出。 然后，把虚拟内存设成8G，重启，就正常运行了

谢谢大佬，我调成16G的虚拟内存可以正常下载了

**Comment by xyshyniaphy** [comment]
好的，参照别人的反馈和自己的观察，模型加载，总共占了55G内存
