### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 15.34 GiB is free.

### ISSUE THREAD

**Issue by aminsaiful** [lllyasviel/FramePack#132]
PS D:\framepack_cu126_torch26> .\run.bat
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
Namespace(share=False, server='127.0.0.1', port=None, inbrowser=True)
Free VRAM 22.759765625 GB
High-VRAM Mode: False
Downloading shards: 100%|███████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 797.78it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  5.46it/s]
Fetching 3 files: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 3118.44it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 12.71it/s]
transformer.high_quality_fp32_output_for_inference = True
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Unloaded CLIPTextModel as complete.
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Loaded SiglipVisionModel to cuda:0 as complete.
latent_padding_size = 27, is_last_section = False
Unloaded SiglipVisionModel as complete.
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 6 GB
Traceback (most recent call last):
  File "D:\framepack_cu126_torch26\webui\demo_gradio.py", line 216, in worker
    move_model_to_device_with_memory_preservation(transformer, target_device=gpu, preserved_memory_gb=gpu_memory_preservation)
  File "D:\framepack_cu126_torch26\webui\diffusers_helper\memory.py", line 92, in move_model_to_device_with_memory_preservation
    if hasattr(m, 'weight'):
  File "D:\framepack_cu126_torch26\webui\diffusers_helper\memory.py", line 26, in hacked_get_attr
    return torch.nn.Parameter(p.to(**kwargs), requires_grad=p.requires_grad)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 15.34 GiB is free. Of the allocated memory 7.33 GiB is allocated by PyTorch, and 33.95 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Press any key to continue . . .

**Comment by TigerFox57** [comment]
I have similar issues. I suspect it's something to do with my lack of RAM, which is just 16GB. I have 16GB of VRAM.

**Comment by tool2d** [comment]
This error occurs because your system doesn't have an NVIDIA 30xx or 40xx series graphics card. The program automatically falls back from BF16 to a larger floating-point format, which results in the out-of-memory error.

**Comment by rayqianhua** [comment]
i have RTX 4060 8GB with the same error. It might need update CUDA to 12.6.

**Comment by flakeforever** [comment]
check #26

**Comment by aminsaiful** [comment]
> I have similar issues. I suspect it's something to do with my lack of RAM, which is just 16GB. I have 16GB of VRAM.

My PC have 64GB RAM
And RTX 3090

**Comment by Grey3016** [comment]
You're running the bat from powershell, have you tried double clicking it?

**Comment by villaratio** [comment]
Same issue.
I use an RTX 4070 with 12GB VRAM (and 32 GB normal memory).

**Comment by microbenh** [comment]
Me too, with RTX 2070s

**Comment by illuculent** [comment]
Same here RTX 4070 16 GB VRAM Python 3.10.6 12.6 Cuda - File "D:\AI\framepack_cu126_torch26\system\python\lib\site-packages\diffusers\models\activations.py", line 85, in gelu
    return F.gelu(gate, approximate=self.approximate)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 404.00 MiB. GPU 0 has a total capacity of 11.99 GiB of which 4.29 GiB is free. Of the allocated memory 5.83 GiB is allocated by PyTorch, and 686.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True var is set.

**Comment by flakeforever** [comment]
> check [#26](https://github.com/lllyasviel/FramePack/issues/26)

Hey guys, if you check this post. You will found that someone made a fork on https://github.com/freely-boss/FramePack-nv20
I'm on 2080ti right now, and it works, no 'CUDA out of memory' anymore.

**Comment by microbenh** [comment]
> > check [#26](https://github.com/lllyasviel/FramePack/issues/26)
> 
> Hey guys, if you check this post. You will found that someone made a fork on https://github.com/freely-boss/FramePack-nv20 I'm on 2080ti right now, and it works, no 'CUDA out of memory' issue anymore.

It works on RTX-2070s

**Comment by wukaikailive** [comment]
My hardware has 128GB RAM and a 2080Ti with 22GB VRAM, but it still encounters out-of-memory issues. After switching to the forked version, it can run, but the speed is unbearably slow.

**Comment by kukalikuk** [comment]
Set your pagefile in your SSD to more than 30GB, it always help whe doing AI stuffs like this.

**Comment by nlitndnostalgic** [comment]
Old Turing generation Quadro RTX 6000 (24GB VRam), 41GB Ram (Shadow cloud PC), Framepack in Comfyui. The problem was solved easily by lowering the target resolution to 320 from 640. With teacache enabled, my last 5-second gen took 925 seconds with the 25GB diffuser pack and the previous one with the fp8 model took 981 seconds. The result looks more detailed and coherent than LTX 0.96 at 200 steps at twice the resolution.
