### ISSUE TITLE
Have encountered video memory problems 遇到了显存爆满问题

### ISSUE THREAD

**Issue by lvyonghuan** [lllyasviel/FramePack#195]
I've had these errors when running.
```
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Error in listener thread: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```
Then I found something Interesting.

![Image](https://github.com/user-attachments/assets/90dd3fd4-bf2b-4479-bc78-25c899aa52e9)

Display dedicated memory is full, and shared memory is also occupied a lot.

Why does this problem occur? I did not change the configuration of the graphical interface. The GPU is M40 24G.

**Comment by lvyonghuan** [comment]
似乎是因为powershell的问题，我直接shift右键打开powershell就会爆显存，但是如果我直接打开一个powershell再切换过去至少可以正常跑。我也不知道为什么了。
不过遇到了一个新的问题，我会新开一个issue。

It seems that because of the powershell problem, I will directly switch to powershell and will explode the video memory, but if I directly open a powershell and switch to it, I can at least run normally. I don't know why.
But I encountered a new problem, I will open a new issue.
