### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.87 GiB.

### ISSUE THREAD

**Issue by gfejer** [lllyasviel/FramePack#233]
I have a Tesla P40 with 24GBs of VRAM and for some reason FramePack wants to allocate 28GBs of VRAM. How can I decrease the VRAM usage?

<img width="607" alt="Image" src="https://github.com/user-attachments/assets/03ec40bb-07e2-4b61-8de7-79cf99d00c8d" />

**Comment by PmNz8** [comment]
I get OOM error for cuda even with settings (preserved memory) as high as 16 GB for RTX 4090. GPU-Z shows only like 8-9 GB of used memory then it crashes, often also making something similar to the driver crash (black screen that recovers after a while).

`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 202.00 MiB. GPU 0 has a total capacity of 23.99 GiB of which 14.98 GiB is free. Of the allocated memory 7.31 GiB is allocated by PyTorch, and 85.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
`

**Comment by gfejer** [comment]
But how are others able to load the model to 6GB GPUs?

**Comment by randomhuman9** [comment]
GTX 1080 with 8GB VRAM - I am also getting this.

**Comment by Tetsujinfr** [comment]
> I have a Tesla P40 with 24GBs of VRAM and for some reason FramePack wants to allocate 28GBs of VRAM. How can I decrease the VRAM usage?
> 
> <img alt="Image" width="607" src="https://private-user-images.githubusercontent.com/73720542/435999899-03ec40bb-07e2-4b61-8de7-79cf99d00c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzMzg1MTMsIm5iZiI6MTc0NTMzODIxMywicGF0aCI6Ii83MzcyMDU0Mi80MzU5OTk4OTktMDNlYzQwYmItMDdlMi00YjYxLThkZTctNzljZjk5ZDAwYzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDIyVDE2MTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGViNGVjM2RlY2E3MDgxNDUyYTJiNWRjM2U1Njk5YTU5MzZlYTIwN2U3ODJjNWQ4NWQ5YTI2OWE4Njc0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QT4jGDUmPYnT0FnfHnotxBBoDU1bLKo9Jz8W32sI5po">

Are you not supposed to increase the gpu inference preserved slider to consume less memory? You screenshot shows 6, which is the minimum value, try 128 instead

**Comment by gfejer** [comment]
> Are you not supposed to increase the gpu inference preserved slider to consume less memory? You screenshot shows 6, which is the minimum value, try 128 instead

I tried it and got the same results. The slider doesn't seem to help.

**Comment by PmNz8** [comment]
Okay, I think that **maybe** I found the case. I got rid of the Cuda OOM error by increasing RAM SWAP size for windows. As you can see, it allocates almost 70 GB despite not really using so much (it does not read/write swap from my disc). But now I managed to go up to full 24 GB of VRAM on my RTX 4090.

![Image](https://github.com/user-attachments/assets/1b740084-8775-4018-bf34-b9ebf473f2c0)

![Image](https://github.com/user-attachments/assets/13066f44-aa11-4352-a909-96c882e7723f)

And the iteration speed improved much thanks to it:

![Image](https://github.com/user-attachments/assets/64cd817b-46c1-46ac-b22d-78c4393d2aa4)

**Comment by Cargo190** [comment]
> Okay, I think that **maybe** I found the case. I got rid of the Cuda OOM error by increasing RAM SWAP size for windows. 

Yeah, that seems to really work. Thank you

**Comment by Confusedfish** [comment]
Unfortunately for me the suggestion of increasing the swap size doesn't help. The shared memory with the GPU is fixed so increasing the available swap memory in the OS doesn't increase the available GPU memory which seems to be the 6GB VRAM + half the system RAM. The system monitor in Windows is showing a maximum of 21.9GB. Any other suggestions?

**Comment by AngelTs** [comment]
Set pagefile.sys to 100GB-300GB and try not to use this drive while compute the video!

**Comment by FP4** [comment]
> Set pagefile.sys to 100GB-300GB and try not to use this drive while compute the video!

tried that, but it did not help

**Comment by lijianaiml** [comment]
> > I have a Tesla P40 with 24GBs of VRAM and for some reason FramePack wants to allocate 28GBs of VRAM. How can I decrease the VRAM usage?
> > <img alt="Image" width="607" src="https://private-user-images.githubusercontent.com/73720542/435999899-03ec40bb-07e2-4b61-8de7-79cf99d00c8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzMzg1MTMsIm5iZiI6MTc0NTMzODIxMywicGF0aCI6Ii83MzcyMDU0Mi80MzU5OTk4OTktMDNlYzQwYmItMDdlMi00YjYxLThkZTctNzljZjk5ZDAwYzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDIyVDE2MTAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGViNGVjM2RlY2E3MDgxNDUyYTJiNWRjM2U1Njk5YTU5MzZlYTIwN2U3ODJjNWQ4NWQ5YTI2OWE4Njc0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QT4jGDUmPYnT0FnfHnotxBBoDU1bLKo9Jz8W32sI5po">
> 
> Are you not supposed to increase the gpu inference preserved slider to consume less memory? You screenshot shows 6, which is the minimum value, try 128 instead

work for me, thanks a lot.

**Comment by gfejer** [comment]
Does anyone have other suggestions? None of these could solve my issue...

**Comment by KishinSR6** [comment]
@AngelTs What and where is that file?

**Comment by AngelTs** [comment]
Virtual memory in WIndows - "Advanced system settings" -> "Performance" -> "Advanced" -> "Virtual memory"=Change -> and set min 50GB(100GB) for selected drive(preferably not used for other things) and press OK and restart

**Comment by ghsable** [comment]
https://github.com/lllyasviel/FramePack/issues/149#issuecomment-2817001980
