### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device on 5070TI

### ISSUE THREAD

**Issue by bobbybob828** [lllyasviel/FramePack#267]
Full issue:

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by woct0rdho** [comment]
Just to clarify the myth: torch 2.7+cu128 is released now, so you can install it to support RTX 50xx, and you don't need to install the nightly (unstable) version.

On Windows, the torch wheel bundles the needed CUDA libraries, so you don't need to install the 'full CUDA toolkit' that takes many GB.

**Comment by Kukee2018** [comment]
> > You need to install pytorch 12.8 for nvidia RTX 5000 GPUs. Follow the Linux installation instructions [here](https://github.com/lllyasviel/FramePack?tab=readme-ov-file#installation) and but use this line instead of the one ending in cu126 `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`
> > edit: torch just released a stable 2.7
> > ~I think you also need to have installed [CUDA Toolkit 12.8](https://developer.nvidia.com/cuda-downloads) from nvidia's website.~
> 
> > Just to clarify the myth: torch 2.7+cu128 is released now, so you can install it to support RTX 50xx, and you don't need to install the nightly (unstable) version.
> > On Windows, the torch wheel bundles the needed CUDA libraries, so you don't need to install the 'full CUDA toolkit' that takes many GB.
> 
> I'm pretty new to everything, how do I install this new version? Where do I go to install it?

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

**Comment by Iggyboo** [comment]
FYI if it says you may need `pip3 install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`  if you already have the previous versions installed rather than trying to uninstall them first.

**Comment by Apokadr** [comment]
Nothing helps, exactly the same problem, I'm afraid it needs some update from the project author, as ComfyUI has already fixed it

To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Traceback (most recent call last):
  File "F:\framepack_cu126_torch26\webui\demo_gradio.py", line 126, in worker
    llama_vec, clip_l_pooler = encode_prompt_conds(prompt, text_encoder, text_encoder_2, tokenizer, tokenizer_2)
  File "F:\framepack_cu126_torch26\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "F:\framepack_cu126_torch26\webui\diffusers_helper\hunyuan.py", line 31, in encode_prompt_conds
    llama_attention_length = int(llama_attention_mask.sum())
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by woct0rdho** [comment]
If you use the one-click package of FramePack, you need to run `pip` in the Python environment bundled with FramePack. It's like
```pwsh
C:\path\to\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```
where you need to change `C:\path\to\framepack_cu126_torch26\` to the actual path of your `C:\path\to\framepack_cu126_torch26\` folder.

**Comment by slow-down** [comment]
> If you use the one-click package of FramePack, you need to run `pip` in the Python environment bundled with FramePack. It's like
> 
> C:\path\to\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> where you need to change `C:\path\to\framepack_cu126_torch26\` to the actual path of your `C:\path\to\framepack_cu126_torch26\` folder.

wait, so yes it does work for the normal video generation with rtx 5000 series when installing cu128 like that, but this way i can't use flash attention because their download only supports 12.6 instead of 12.8... so my rtx 5080 is actually way slower than peoples 4000 series because they can use flash attention :/ or am i missing something. it averages like 10s/iteration on my rtx 5080 which doesn't seem good at all

**Comment by woct0rdho** [comment]
@slow-down You just need SageAttention rather than xformers or FlashAttention. SageAttention is faster than the latter two in most cases with no quality loss. When FramePack finds that SageAttention is installed, it does not use the latter two.

Feel free to install my SageAttention wheels https://github.com/woct0rdho/SageAttention/releases

**Comment by bobbybob828** [comment]
> If you use the one-click package of FramePack, you need to run `pip` in the Python environment bundled with FramePack. It's like
> 
> C:\path\to\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> where you need to change `C:\path\to\framepack_cu126_torch26\` to the actual path of your `C:\path\to\framepack_cu126_torch26\` folder.

Just because I'm new at this, what's the process of running pip in the python environment bundled with Framepack? In the file structure you linked, I see there's a file entitled "python", I'm assuming I have to do something with that?

I tried to copy and paste the -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 that you have there but it didn't do anything

**Comment by woct0rdho** [comment]
@bobbybob828 First, open the terminal window. You can type 'term' in the Start menu and find it. (Some old tutorials use 'cmd' rather than Windows Terminal/PowerShell but that's mostly the same.)

Then type
```
C:\path\to\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```
in the terminal window and press Enter.

If you see anything wrong, please show the command you typed and all the output results.

If you directly open 'python', see something like
```
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
and type the above command there, that will not work.

**Comment by TPN-code** [comment]
> [@slow-down](https://github.com/slow-down) You just need SageAttention rather than xformers or FlashAttention. SageAttention is faster than the latter two with no quality loss in most cases. When FramePack finds that SageAttention is installed, it does not use the latter two.
> 
> Feel free to install my SageAttention wheels https://github.com/woct0rdho/SageAttention/releases

Hello, i tried that, the package is in the library but it still show that its missing.

.\framepack_cu126_torch26 - Copy\system\python>python -m pip list

absl-py                   2.1.0
accelerate                1.6.0
addict                    2.4.0
aenum                     3.1.15
aiofiles                  23.2.1
aiosignal                 1.3.1
albumentations            1.3.1
altair                    5.3.0
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.2.0
av                        12.1.0
basicsr                   1.4.2
blendmodes                2022
certifi                   2024.2.2
charset-normalizer        3.3.2
clean-fid                 0.1.35
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
colorlog                  6.8.2
contourpy                 1.2.0
cycler                    0.12.1
Cython                    3.0.8
deprecation               2.1.0
depth_anything            2024.1.22.0
diffusers                 0.33.1
diskcache                 5.6.3
easydict                  1.11
einops                    0.4.1
embreex                   2.17.7.post4
exceptiongroup            1.2.0
facexlib                  0.3.0
fastapi                   0.115.12
ffmpy                     0.3.1
filelock                  3.13.1
filterpy                  1.4.5
flatbuffers               25.2.10
fonttools                 4.47.2
frozenlist                1.4.1
fsspec                    2024.6.1
ftfy                      6.1.3
future                    0.18.3
gitdb                     4.0.11
gradio                    5.23.0
gradio_client             1.8.0
gradio_rangeslider        0.0.6
groovy                    0.1.2
grpcio                    1.60.1
h11                       0.12.0
handrefinerportable       2024.2.12.0
httpcore                  0.15.0
httpx                     0.24.1
huggingface-hub           0.30.2
humanfriendly             10.0
idna                      3.6
imageio                   2.33.1
importlib-metadata        7.0.1
inflection                0.5.1
insightface               0.7.3
Jinja2                    3.1.4
joblib                    1.3.2
jsonmerge                 1.8.0
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kornia                    0.6.7
lark                      1.1.2
lazy_loader               0.3
lightning-utilities       0.10.1
llvmlite                  0.42.0
lmdb                      1.4.1
mapbox-earcut             1.0.1
Markdown                  3.5.2
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.8.2
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.5
networkx                  3.3
numba                     0.59.0
numpy                     1.26.2
omegaconf                 2.2.3
onnx                      1.15.0
onnxruntime               1.17.0
opencv-contrib-python     4.9.0.80
opencv-python             4.10.0.84
opencv-python-headless    4.9.0.80
orjson                    3.9.13
packaging                 23.2
pandas                    2.2.0
piexif                    1.1.3
pillow                    11.1.0
pillow-avif-plugin        1.4.3
pip                       25.0.1
platformdirs              4.2.0
prettytable               3.9.0
protobuf                  3.20.0
psutil                    5.9.5
pycollada                 0.8
pydantic                  2.8.2
pydantic_core             2.20.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.1.1
pyreadline3               3.4.1
python-dateutil           2.8.2
python-multipart          0.0.20
pytz                      2024.1
PyWavelets                1.5.0
PyYAML                    6.0.1
qudida                    0.0.4
referencing               0.33.0
regex                     2023.12.25
requests                  2.31.0
resize-right              0.0.2
rich                      13.7.1
rpds-py                   0.17.1
Rtree                     1.2.0
ruff                      0.11.6
safehttpx                 0.1.6
safetensors               0.5.3
sageattention             2.1.1+cu128torch2.7.0
scikit-image              0.21.0
scikit-learn              1.4.0
scipy                     1.12.0
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                69.5.1
shapely                   2.0.2
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.0
spandrel                  0.3.4
spandrel_extra_arches     0.1.1
starlette                 0.46.2
svg.path                  6.3
sympy                     1.13.3
tb-nightly                2.16.0a20240204
tensorboard-data-server   0.7.2
tf_keras-nightly          2.16.0.dev2024020410
threadpoolctl             3.2.0
tifffile                  2024.1.30
tokenizers                0.20.3
tomli                     2.0.1
tomlkit                   0.12.0
toolz                     0.12.1
torch                     2.7.0+cu128
torchaudio                2.7.0+cu128
torchdiffeq               0.2.3
torchmetrics              1.3.0.post0
torchsde                  0.2.6
torchvision               0.22.0+cu128
tqdm                      4.67.1
trampoline                0.1.2
transformers              4.46.2
trimesh                   4.1.3
typer                     0.12.3
typing_extensions         4.12.2
tzdata                    2023.4
urllib3                   2.2.0
uvicorn                   0.27.0.post1
vhacdx                    0.0.5
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  3.0.1
wheel                     0.42.0
yapf                      0.40.2
yarl                      1.9.4
zipp                      3.17.0

**Comment by woct0rdho** [comment]
@TPN-code Before installing SageAttention, you need to install Triton, see https://github.com/woct0rdho/triton-windows

**Comment by TPN-code** [comment]
That worked, thank you!

> [@TPN-code](https://github.com/TPN-code) Before installing SageAttention, you need to install Triton, see https://github.com/woct0rdho/triton-windows

**Comment by bobbybob828** [comment]
> [@bobbybob828](https://github.com/bobbybob828) First, open the terminal window. You can type 'term' in the Start menu and find it. You'll see a window showing something like
> 
> ```
> PowerShell 7.5.1
> PS C:\Users\wocto>
> ```
> 
> (Some old tutorials use 'cmd' rather than Windows Terminal/PowerShell but that's mostly the same.)
> 
> Then paste the command
> 
> ```
> C:\path\to\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> ```
> 
> in the terminal window and press Enter.
> 
> If you see anything wrong, please show the command you ran and all the output results.
> 
> But, if you directly click 'python', see something like
> 
> ```
> Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>>
> ```
> 
> and type the above command there, that will not work. That's the interactive command line inside Python, not the Windows system.

It's working now, thank you! I did get this error at the very end of the install, but maybe it's a non-issue because the program is working now

Installing collected packages: sympy, torch, torchvision, torchaudio
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
  WARNING: The script isympy.exe is installed in 'C:\path\to\framepack_cu126_torch26\framepack_cu126_torch26\system\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0+cu126
    Uninstalling torch-2.6.0+cu126:
      Successfully uninstalled torch-2.6.0+cu126
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\path\to\framepack_cu126_torch26\framepack_cu126_torch26\system\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.21.0+cu126
    Uninstalling torchvision-0.21.0+cu126:
      Successfully uninstalled torchvision-0.21.0+cu126
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.6.0+cu126
    Uninstalling torchaudio-2.6.0+cu126:
      Successfully uninstalled torchaudio-2.6.0+cu126
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnxruntime 1.17.0 requires flatbuffers, which is not installed.
Successfully installed sympy-1.13.3 torch-2.7.0+cu128 torchaudio-2.7.0+cu128 torchvision-0.22.0+cu128

if nothing here looks wrong then it seems to be in working order

**Comment by woct0rdho** [comment]
@bobbybob828 You can ignore the error `onnxruntime 1.17.0 requires flatbuffers, which is not installed.` for now, because ONNX is actually not used in FramePack. Actually I think this one-click package includes a lot of unnecessary things.

**Comment by bobbybob828** [comment]
> [@bobbybob828](https://github.com/bobbybob828) Ok there looks no problem. You can ignore the error `onnxruntime 1.17.0 requires flatbuffers, which is not installed.` for now, because ONNX is actually not used in FramePack. Actually I think this one-click package includes a lot of unnecessary things.
> 
> You can also ignore the warnings like `WARNING: The script isympy.exe is installed in .. which is not on PATH.` because it's an embedded Python installation.

Thanks so much for the help :)

**Comment by danaththetiger** [comment]
> [@bobbybob828](https://github.com/bobbybob828) Ok there looks no problem. You can ignore the error `onnxruntime 1.17.0 requires flatbuffers, which is not installed.` for now, because ONNX is actually not used in FramePack. Actually I think this one-click package includes a lot of unnecessary things.
> 
> You can also ignore the warnings like `WARNING: The script isympy.exe is installed in .. which is not on PATH.` because it's an embedded Python installation.

Had the exact same issue, now fixed. Thank you for the help!
