### ISSUE TITLE
FramePack triggers CUDA OOM (>30GB allocation) on 8GB GPU, even with minimal inputs

### ISSUE THREAD

**Issue by FENBIANKELI** [lllyasviel/FramePack#271]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 30.26 GiB. GPU 0 has a total capacity of 8.00 GiB of which 3.90 GiB is free. Of the allocated memory 2.62 GiB is allocated by PyTorch, and 446.42 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.

**Comment by PmNz8** [comment]
Try to increase RAM SWAP size:

https://github.com/lllyasviel/FramePack/issues/233#issuecomment-2821970530

**Comment by FENBIANKELI** [comment]
> Try to increase RAM SWAP size:
> 
> [#233 (comment)](https://github.com/lllyasviel/FramePack/issues/233#issuecomment-2821970530)
> 
> For me, I have 32 GB of physical ram, and had to increase swap to over 40 GB, so I would have >70 GB available for allocation.

Thanks for the suggestion. I actually increased my swap space to over 200 GB, but the issue still persists.

**Comment by philosadelphos** [comment]
Same issue here:
`torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.85 GiB. GPU 0 has a total capacity of 5.93 GiB of which 2.63 GiB is free. Including non-PyTorch memory, this process has 3.17 GiB memory in use. Of the allocated memory 2.78 GiB is allocated by PyTorch, and 312.01 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
^CKeyboard interruption in main thread... closing server.
`

**Comment by FP4** [comment]
also Out of memory on 2060 Super with 8GB VRAM, 64GB RAM, with bit of a twist that in the error message it says "0 bytes is free." about the VRAM, (on the start of Framepack it says "Free VRAM 6.984375 GB", and yeah its filled up by the point when the error comes up) 
> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 29.75 GiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 32.34 GiB is allocated by PyTorch, and 512.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by nlitndnostalgic** [comment]
Same here with an older 24GB VRam card (Nvidia Turing architecture - no sage attention support and neither xformers or flash-attention installed). I simply lowered the target resolution by half in Comfy, from 640 to 320 and it did the trick.

**Comment by FENBIANKELI** [comment]
> also Out of memory on 2060 Super with 8GB VRAM, 64GB RAM, with bit of a twist that in the error message it says "0 bytes is free." about the VRAM, (on the start of Framepack it says "Free VRAM 6.984375 GB", and yeah its filled up by the point when the error comes up)
> 
> > torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 29.75 GiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 32.34 GiB is allocated by PyTorch, and 512.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Same here. I'm also using a 2060 Super with 8GB VRAM.

**Comment by FENBIANKELI** [comment]
By the way, I was wondering if the problem could be related to lack of bf16 support.
Since 2060 Super (Turing architecture) doesn't support bf16, everything runs in float32, which doubles VRAM usage compared to mixed precision.
However, even accounting for that, the memory explosion (30GB+) seems excessive, suggesting the issue might be deeper — likely due to how FramePack handles tensor memory on GPU.

**Comment by capic2** [comment]
> By the way, I was wondering if the problem could be related to lack of bf16 support. Since 2060 Super (Turing architecture) doesn't support bf16, everything runs in float32, which doubles VRAM usage compared to mixed precision. However, even accounting for that, the memory explosion (30GB+) seems excessive, suggesting the issue might be deeper — likely due to how FramePack handles tensor memory on GPU.

I have the same issue with an old gtx 1660 6gb

**Comment by sunrisesineast** [comment]
Same error gtx 2060
