### ISSUE TITLE
I got cuda error with my RTX 5090!!

### ISSUE THREAD

**Issue by merecesarchviz** [lllyasviel/FramePack#31]
I install all correct without errors but when i try to generate i got this errors:

* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Traceback (most recent call last):
  File "C:\AI\FramePack\demo_gradio.py", line 122, in worker
    llama_vec, clip_l_pooler = encode_prompt_conds(prompt, text_encoder, text_encoder_2, tokenizer, tokenizer_2)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\FramePack\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\FramePack\diffusers_helper\hunyuan.py", line 31, in encode_prompt_conds
    llama_attention_length = int(llama_attention_mask.sum())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Unloaded CLIPTextModel as complete.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.

any idea what is causing it and how i can solve?

**Comment by AznamirWoW** [comment]
for 5000 series you need to install nightly torch with cu128 and Cuda Toolkit 12.8.
`pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`

**Comment by FLIPLETS** [comment]
where do we input this command?

**Comment by AznamirWoW** [comment]
> where do we input this command?

assuming you're using a virtual environment created in FramePack folder, activate it from cmd.exe, then run pip command

**Comment by FLIPLETS** [comment]
environment.bat's 8th line says "set SKIP_VENV=1", wouldnt a venv just not work? If that doesnt mean anything, how would one create a virtual environment in the framepack folder? Isn't the software supposed to be all-in-one and prepackaged?

**Comment by merecesarchviz** [comment]
so i got it working with,

Python 3.10, cu128

doing this install:

python -m pip install --upgrade pip

pip install --pre torch==2.7.0.dev20250311 torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

pip install https://huggingface.co/MonsterMMORPG/SECourses_Premium_Flash_Attention/resolve/main/flash_attn-2.7.4.post1-cp310-cp310-win_amd64.whl

pip install https://files.pythonhosted.org/packages/3d/65/1a6394f5d6dee851e9ea59e385f6d6428e3bfe36f83c06e0336e14dcfd11/deepspeed-0.16.4-cp310-cp310-win_amd64.whl

pip install https://github.com/woct0rdho/SageAttention/releases/download/v2.1.1-windows/sageattention-2.1.1+cu128torch2.7.0-cp310-cp310-win_amd64.whl

pip install -U --pre triton-windows

pip install torchao

pip install -r requirements.txt

**Comment by geriatricpollywog** [comment]
I have the same error message with my 5090. I tried AznamirWoW's suggestion and it did not fix.

**Comment by udkyo** [comment]
> where do we input this command?

I put an upgrade step in run.bat to get mine working (thanks @AznamirWoW!)

```
...

cd %~dp0webui

"%DIR%\python\python.exe" -m pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

"%DIR%\python\python.exe" demo_gradio.py --server 127.0.0.1 --inbrowser
...

```

**Comment by hwprinz** [comment]
does this upgrade work?
i had the same on ComfyUI, and had to use 'pip install --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128'
'--upgrade' does not upgrade

**Comment by geriatricpollywog** [comment]
> > where do we input this command?
> 
> I put an upgrade step in run.bat to get mine working (thanks [@AznamirWoW](https://github.com/AznamirWoW)!)
> 
> ```
> ...
> 
> cd %~dp0webui
> 
> "%DIR%\python\python.exe" -m pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> "%DIR%\python\python.exe" demo_gradio.py --server 127.0.0.1 --inbrowser
> ...
> ```

This worked for me too!

**Comment by catclaw** [comment]
Hi!

I get this error after adding the line to run.bat:
onnxruntime 1.17.0 requires flatbuffers, which is not installed.


->
download.pytorch.org/whl/nightly/cu128
Looking in indexes: https://download.pytorch.org/whl/nightly/cu128
Requirement already satisfied: torch in l:\framepack\system\python\lib\site-packages (2.6.0+cu126)
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu128/torch-2.8.0.dev20250427%2Bcu128-cp310-cp310-win_amd64.whl (3131.9 MB)
     ---------------------------------------- 3.1/3.1 GB 359.7 kB/s eta 0:00:00
Requirement already satisfied: torchvision in l:\framepack\system\python\lib\site-packages (0.21.0+cu126)
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/cu128/torchvision-0.22.0.dev20250427%2Bcu128-cp310-cp310-win_amd64.whl.metadata (6.3 kB)
Requirement already satisfied: torchaudio in l:\framepack\system\python\lib\site-packages (2.6.0+cu126)
Requirement already satisfied: filelock in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from torch) (3.13.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from torch) (4.13.0)
Collecting sympy>=1.13.3 (from torch)
  Using cached https://download.pytorch.org/whl/nightly/sympy-1.13.3-py3-none-any.whl (6.2 MB)
Requirement already satisfied: networkx in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from torch) (2024.3.1)
Requirement already satisfied: numpy in l:\framepack\system\python\lib\site-packages (from torchvision) (1.26.2)
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cu128/torch-2.8.0.dev20250426%2Bcu128-cp310-cp310-win_amd64.whl.metadata (29 kB)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in l:\framepack\system\python\lib\site-packages (from torchvision) (11.1.0)
INFO: pip is looking at multiple versions of torchaudio to determine which version is compatible with other requirements. This could take a while.
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/cu128/torchaudio-2.6.0.dev20250427%2Bcu128-cp310-cp310-win_amd64.whl.metadata (7.3 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\iman mirbioki\appdata\roaming\python\python310\site-packages (from jinja2->torch) (2.1.5)
Downloading https://download.pytorch.org/whl/nightly/cu128/torchvision-0.22.0.dev20250427%2Bcu128-cp310-cp310-win_amd64.whl (7.6 MB)
   ---------------------------------------- 7.6/7.6 MB 69.4 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/nightly/cu128/torch-2.8.0.dev20250426%2Bcu128-cp310-cp310-win_amd64.whl (3131.9 MB)
   ---------------------------------------- 3.1/3.1 GB 369.8 kB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/nightly/cu128/torchaudio-2.6.0.dev20250427%2Bcu128-cp310-cp310-win_amd64.whl (4.7 MB)
   ---------------------------------------- 4.7/4.7 MB 59.5 MB/s eta 0:00:00
Installing collected packages: sympy, torch, torchvision, torchaudio
  Attempting uninstall: sympy
    Found existing installation: sympy 1.13.1
    Uninstalling sympy-1.13.1:
      Successfully uninstalled sympy-1.13.1
  WARNING: The script isympy.exe is installed in 'L:\framepack\system\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torch
    Found existing installation: torch 2.6.0+cu126
    Uninstalling torch-2.6.0+cu126:
      Successfully uninstalled torch-2.6.0+cu126
  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'L:\framepack\system\python\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.21.0+cu126
    Uninstalling torchvision-0.21.0+cu126:
      Successfully uninstalled torchvision-0.21.0+cu126
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.6.0+cu126
    Uninstalling torchaudio-2.6.0+cu126:
      Successfully uninstalled torchaudio-2.6.0+cu126
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnxruntime 1.17.0 requires flatbuffers, which is not installed.
Successfully installed sympy-1.13.3 torch-2.8.0.dev20250426+cu128 torchaudio-2.6.0.dev20250427+cu128 torchvision-0.22.0.dev20250427+cu128

**Comment by pocketpoetry** [comment]
See if following this walk-through works

https://youtu.be/dkqFtu0v_eY?si=D8TQsgkjfYmUXepj
