### ISSUE TITLE
Error: CUDA out of memory.

### ISSUE THREAD

**Issue by robbiboy** [lllyasviel/FramePack#351]
I have the Quadro P4000 GPU with 8 GB of dedicated VRAM plus 63.8 GB of shared memory. I tried the
`PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`
described in the error but it doesn't work.

Here is the full error message:
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.57 GiB. GPU 0 has a total capacity of 8.00 GiB of which 0 bytes is free. Of the allocated memory 63.24 GiB is allocated by PyTorch, and 300.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by Ok2dot0** [comment]
Same issue here. On a 2060 with 12GB VRAM

Here is the log

[log.txt](https://github.com/user-attachments/files/19923176/log.txt)

**Comment by TejasPlayzYT** [comment]
I am using a Quadro P2200 and cannot do anything with this.

**Comment by Ok2dot0** [comment]
https://github.com/freely-boss/FramePack-nv20
I will try out this fork. Maybe it will fix it

**Comment by cguriuoc** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

That fork worked for me with an rtx 2060

**Comment by robbiboy** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

I will try this

**Comment by robbiboy** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

I'm getting a new issue now... TLDR: "**error: externally-managed-environment"**

**Comment by dandarm** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

it worked also for me!!!

**Comment by robbiboy** [comment]
> > https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it
> 
> I'm getting a new issue now... TLDR: "**error: externally-managed-environment"**

It turns out I forgot to install the miniconda and set-up an environment. Is that the solution to the "externally managed environment" problem or shoulda I done something different?
Anyway, I want to ask if this is normal. The web-gui is stuck at "start sampling" and terminal is stuck like this --->

![Image](https://github.com/user-attachments/assets/e56aea5e-9e10-4be6-b381-670bc92fe258)

**Comment by andoryu-kun** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

Works for me on RTX 2060 Super 8GB. Thanks.

**Comment by gloryomoye** [comment]
> https://github.com/freely-boss/FramePack-nv20 I will try out this fork. Maybe it will fix it

OMG! This works for me. I have been on this for weeks now. 

Thank you so much for sharing
