### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by dps1979S** [lllyasviel/FramePack#357]
After installation in windows I receive the following error when i try to create a video:

Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
C:\Users\D\Downloads\framepack_cu126_torch26\system\python\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Namespace(share=False, server='127.0.0.1', port=None, inbrowser=True)
Free VRAM 14.5185546875 GB
High-VRAM Mode: False
Downloading shards: 100%|██████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 3995.53it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.21it/s]
Fetching 3 files: 100%|████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 2986.69it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  4.58it/s]
transformer.high_quality_fp32_output_for_inference = True
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Traceback (most recent call last):
  File "C:\Users\D\Downloads\framepack_cu126_torch26\webui\demo_gradio.py", line 126, in worker
    llama_vec, clip_l_pooler = encode_prompt_conds(prompt, text_encoder, text_encoder_2, tokenizer, tokenizer_2)
  File "C:\Users\D\Downloads\framepack_cu126_torch26\system\python\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\D\Downloads\framepack_cu126_torch26\webui\diffusers_helper\hunyuan.py", line 31, in encode_prompt_conds
    llama_attention_length = int(llama_attention_mask.sum())
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Unloaded CLIPTextModel as complete.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.

I have:
processor: Intel(R) Core(TM) Ultra 9 285K   3.70 GHz
graphics card: NVIDIA GeForce RTX 5080

**Comment by lazyfish** [comment]
For a 50x gpu 
```
pip uninstall torch torchvision torchaudio 
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```

**Comment by lonelygoogle** [comment]
Hi, @lazyfish. I did as your steps but still did not work.  My GPU is 5080Ti with CUDA 12.8 and python 3.10.6, Any idea about is？
`Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
D:\AI\FramePack\framepack_cu126_torch26\framepack_cu126_torch26\system\python\lib\site-packages\torch\cuda\__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/`

**Comment by woct0rdho** [comment]
@lonelygoogle You need to run the pip command in the Python environment provided by FramePack. It's like
```pwsh
C:\Users\D\Downloads\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```

BTW, the stable version of torch 2.7 is released, so we don't need to install the nightly version

**Comment by lazyfish** [comment]
I guess if you're on Windows and downloaded the standalone framepack archive you need to run the environment.bat first in cmd or wherever you do it, and run the scripts after that, so it updates the python modules in the provided system folder.

**Comment by lonelygoogle** [comment]
Thank you very much! @woct0rdho, let me try using the your step upgrate pytorch. The key is my pytorch cannot support sm120, I cannot see if torch 2.7 or nightly support sm120 in pytorch official website.

**Comment by lonelygoogle** [comment]
Thank you very much! @lazyfish  Yes, I am on Win11 and downloaded from [>>> Click Here to Download One-Click Package (CUDA 12.6 + Pytorch 2.6) <<<](https://github.com/lllyasviel/FramePack/releases/download/windows/framepack_cu126_torch26.7z).
After run  environment.bat in my cmd, do I need to unistall old pytorch in my virtal environment (in folder venv) and install pytorch that supports sm120?

**Comment by woct0rdho** [comment]
When you run `pip install --upgrade`, it will automatically uninstall the old version and install the new version.

Without `--upgrade`, it may not upgrade the already installed version.

It will also work if you follow lazyfish's advice to first manually uninstall the old version, then install the new version.

**Comment by lonelygoogle** [comment]
Thanks @woct0rdho  After I executed the your command, the error happened.
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnxruntime 1.17.0 requires flatbuffers, which is not installed.
Successfully installed sympy-1.13.3 torch-2.7.0+cu128 torchaudio-2.7.0+cu128 torchvision-0.22.0+cu128` 
But the time I can start the video generation without sm 120 error. I think it is working now, though it is 20 mins passed , 5s video still in progress. Does the slow speed related to flatbuffers not installed?
My GPU is 5070ti, which should generated more quickly as other persons' example.

**Comment by woct0rdho** [comment]
You need to install `flatbuffers` (or rather, properly install `onnxruntime`) if one day you need to use ONNX models. But for now, it's not related to FramePack.

Next you can install Triton and SageAttention to make it faster, see https://github.com/woct0rdho/SageAttention/releases

**Comment by lonelygoogle** [comment]
Thank you very much for your help, @woct0rdho @lazyfish

**Comment by lonelygoogle** [comment]
Hi, @woct0rdho. I successfully tranferred image to video the day before yesterday. But yesterday I start another ImageToVideo, error. So I run Sanity Check as guided as , still this error. I guess it might be related to my 5080Ti sm120 issues? Any idea about it? Thank you very much!
```powershell
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
Namespace(share=False, server='127.0.0.1', port=None, inbrowser=True)
Free VRAM 14.5732421875 GB
High-VRAM Mode: False
Downloading shards: 100%|██████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 3990.77it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.18it/s]
Fetching 3 files: 100%|██████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.97it/s]
transformer.high_quality_fp32_output_for_inference = True
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Unloaded CLIPTextModel as complete.
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Loaded SiglipVisionModel to cuda:0 as complete.
latent_padding_size = 27, is_last_section = False
Unloaded SiglipVisionModel as complete.
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 16 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [06:34<00:00, 15.77s/it]
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
D:\AI\FramePack\framepack_cu126_torch26\framepack_cu126_torch26\system\python\lib\site-packages\torchvision\io\_video_deprecation_warning.py:5: UserWarning: The video decoding and encoding capabilities of torchvision are deprecated from version 0.22 and will be removed in version 0.24. We recommend that you migrate to TorchCodec, where we'll consolidate the future decoding/encoding capabilities of PyTorch: https://github.com/pytorch/torchcodec
  warnings.warn(
Decoded. Current latent shape torch.Size([1, 16, 9, 64, 96]); pixel shape torch.Size([1, 3, 33, 512, 768])
latent_padding_size = 18, is_last_section = False
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 16 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [06:01<00:00, 14.48s/it]
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Decoded. Current latent shape torch.Size([1, 16, 18, 64, 96]); pixel shape torch.Size([1, 3, 69, 512, 768])
latent_padding_size = 9, is_last_section = False
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 16 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [06:01<00:00, 14.46s/it]
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Decoded. Current latent shape torch.Size([1, 16, 27, 64, 96]); pixel shape torch.Size([1, 3, 105, 512, 768])
latent_padding_size = 0, is_last_section = True
Moving DynamicSwap_HunyuanVideoTransformer3DModelPacked to cuda:0 with preserved memory: 16 GB
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [05:59<00:00, 14.39s/it]
Offloading DynamicSwap_HunyuanVideoTransformer3DModelPacked from cuda:0 to preserve memory: 8 GB
Loaded AutoencoderKLHunyuanVideo to cuda:0 as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Decoded. Current latent shape torch.Size([1, 16, 37, 64, 96]); pixel shape torch.Size([1, 3, 145, 512, 768])
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
```

**Comment by woct0rdho** [comment]
Try this https://github.com/lllyasviel/FramePack/issues/13#issuecomment-2832591575

This is actually a know issue of aiohttp and will be fixed in aiohttp 4.0 . This is not related to the GPU.

**Comment by lonelygoogle** [comment]
Hi, @woct0rdho. I just saw the tickets after I asked you. Thank you all the same!

**Comment by pocketpoetry** [comment]
Can try following this walk-through to install for rtx 50 series

https://youtu.be/dkqFtu0v_eY?si=D8TQsgkjfYmUXepj

**Comment by lonelygoogle** [comment]
Thanks @pocketpoetry  How did you find this youtbue page

**Comment by hanajlh90** [comment]
![Image](https://github.com/user-attachments/assets/3453ad86-7fa9-4f42-8758-53ca29b7fdd1)

![Image](https://github.com/user-attachments/assets/2bd52d06-57a1-4d78-98d2-8401d7c0adc4)

I am using Win11, Downloaded packages for  [ ["Packing Input Frame Context in Next-Frame Prediction Models for Video Generation"](https://lllyasviel.github.io/frame_pack_gitpage/).](https://github.com/lllyasviel/FramePack/releases/download/windows/framepack_cu126_torch26.7z) 
Is the version incompatible? How do we need to solve it? Thank you.

**Comment by Magnarks** [comment]
> [@lonelygoogle](https://github.com/lonelygoogle) You need to run the pip command in the Python environment provided by FramePack. It's like
> 
> C:\Users\D\Downloads\framepack_cu126_torch26\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> BTW, the stable version of torch 2.7 is released, so we don't need to install the nightly version

Work with my 5070 Ti

But Sage Attention not install:

PS D:\framepack_cu126_torch26\framepack_cu126_torch26\system\python> python.exe -m pip install https://github.com/woct0rdho/SageAttention/releases/download/v2.2.0-windows/sageattention-2.2.0+cu128torch2.7.1-cp310-cp310-win_amd64.whl
ERROR: sageattention-2.2.0+cu128torch2.7.1-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

**Comment by nikil1506** [comment]
Got this issue right now. Latest version of cuda isnt compatible with xformers I guess
