### ISSUE TITLE
torch.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by Alisa121212** [lllyasviel/FramePack#382]
"Requirements:

Nvidia GPU in RTX 30XX, 40XX, 50XX series that supports fp16 and bf16. The GTX 10XX/20XX are not tested.
Linux or Windows operating system.
At least 6GB GPU memory."

But at 8 gb 2070 super i get error: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 31.25 GiB. GPU 0 has a total capacity of 8.00 GiB of which 3.66 GiB is free. Of the allocated memory 2.86 GiB is allocated by PyTorch, and 424.57 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by AndreyRGW** [comment]
I’m hitting the same issue on my end – I get a CUDA out-of-memory error even on an RTX 2060 with 12 GB VRAM, backed by 32 GB system RAM and a 90 GB pagefile.

**Comment by Rolf-100R** [comment]
I have the same thing

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 544.00 MiB. GPU 0 has a total capacity of 12.00 GiB of which 6.47 GiB is free. Of the allocated memory 3.36 GiB is allocated by PyTorch, and 1.07 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by cotrunder** [comment]
I got the same error, on a 3090 (24GB):

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB. GPU 0 has a total capacity of 24.00 GiB of which 12.95 GiB is free. Of the allocated memory 9.72 GiB is allocated by PyTorch, and 33.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

i've added "set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" to envirnment.bat, and still get the error

**Comment by roguefalcon** [comment]
This fixed it for me:

`export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`

It would run the first series of steps and then crash as it went to switch models.  This gave PyTorch what it needed to allow the loading and unloading of models.  I'm on a 3060 Ti with only 6GB of RAM.

**Comment by RoguePigeon** [comment]
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

Where do you type this in? Do you just open a CMD and type it in?

**Comment by warrockmill** [comment]
> This fixed it for me:
> 
> `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`
> 
> It would run the first series of steps and then crash as it went to switch models. This gave PyTorch what it needed to allow the loading and unloading of models. I'm on a 3060 Ti with only 6GB of RAM.

Same question, where should I be running this? In the Cmd window for Python or somewhere else?

**Comment by dilectiogames** [comment]
> `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`

you're do you put this!!??

**Comment by BuckarooBanzai88** [comment]
> > `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`
> 
> you're do you put this!!??

i believe that command is for Linux machines. 
On Windows you can either open a cmd window and use:
set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
then
run.bat

or you can modify the run.bat file and add:  "set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" (without quotes) to the top of the file.

**Comment by dilectiogames** [comment]
> or you can modify the run.bat file and add: "set PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" (without quotes) to the top of the file.

I've found out that certain nvidia cards do not support this command
