### ISSUE TITLE
Compatibility issue between FramePack and RTX 5090 – CUDA Error

### ISSUE THREAD

**Issue by Poufio-bit** [lllyasviel/FramePack#446]
Hello everyone,

I'm currently experiencing an issue trying to run FramePack on my system equipped with an RTX 5090. Despite installing the latest PyTorch nightly build (2.8.0.dev20250501+cu128) and CUDA Toolkit 12.8, I encounter the following error during execution:

vbnet
Copier
Modifier
RuntimeError: CUDA error: no kernel image is available for execution on the device
I’ve tried several solutions, including updating NVIDIA drivers and reinstalling PyTorch with the appropriate options, but the issue persists.

My setup:

GPU: NVIDIA RTX 5090

OS: Windows 11 Pro

Python: 3.10.11

CUDA Toolkit: 12.8

PyTorch: 2.8.0.dev20250501+cu128

I’m aware that the RTX 50 series is relatively new and compatibility issues might occur. If anyone has encountered a similar problem or has suggestions to resolve this error, I’d really appreciate your help.

Thanks in advance for your support!

**Comment by pocketpoetry** [comment]
I followed this process and it works for a 5080

https://youtu.be/dkqFtu0v_eY?si=FxCf1dqfz-gQuVSc

**Comment by mikecastrodemaria** [comment]
same probleme sorry for duplicate :
https://github.com/lllyasviel/FramePack/issues/539

**Comment by mikecastrodemaria** [comment]
> I followed this process and it works for a 5080
> 
> https://youtu.be/dkqFtu0v_eY?si=FxCf1dqfz-gQuVSc

cant see your video , this video is private

**Comment by Auswolf-debug** [comment]
> same probleme sorry for duplicate : [#539](https://github.com/lllyasviel/FramePack/issues/539)

I just installed 5060ti, and all went smoothly.

reinstalled widows, used latest nvidia drivers.  link to pytorch below.
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

With that being said, im suffering from slowness. but i dont think this is related to framepack or torch.
but appears to be problem with python.

**Comment by starfrut** [comment]
PyTorch does not officially support the RTX 5090 yet. Even the newest PyTorch wheels do not include CUDA kernels for sm_120, so you will get errors if you try to use the GPU. You’ll have to wait for official support, or attempt a custom source build (which is very advanced and not recommended for most users)

**Comment by Auswolf-debug** [comment]
Support for the SM_120 architecture, found in NVIDIA's Blackwell series GPUs like the RTX 5000/6000 and RTX 5090/5080, is available in PyTorch 2.7.0 and later, as well as in nightly builds using CUDA 12.8. To utilize these GPUs with PyTorch, ensure you have a compatible PyTorch version installed. If encountering issues, verify that the correct CUDA version (12.8 or later) is installed and that PyTorch is built with support for the SM_120 architecture.

Working install I have for a 5060ti
Windows native
Latest Nvidia drivers
Cuda 12.9
Pytorch 2.7.0
Triton-windows
Xformers
Sage attention
