### ISSUE TITLE
RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.

### ISSUE THREAD

**Issue by SeanWang918** [lllyasviel/FramePack#526]
OS : win11
Python 3.13.3
Video Card: RTX 5060 Ti 16Gb
CUDA: Toolkit 12.8 or 12.9

i tried :
pip uninstall torch torchvision torchaudio

pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
OR
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

but still got error :

![Image](https://github.com/user-attachments/assets/12e16f52-e2bb-496a-bd63-cdc041186f62)

Is there anyone who can help me?

**Comment by woct0rdho** [comment]
You need to run pip in the correct Python environment, see https://github.com/lllyasviel/FramePack/issues/403

**Comment by SeanWang918** [comment]
@woct0rdho tks

another question：
how can I install Flash Attn in windows11 ？ 
I have tried many solutions, but the installation has always failed.

**Comment by woct0rdho** [comment]
Usually you just need SageAttention, see https://github.com/lllyasviel/FramePack/issues/520#issuecomment-2868814117

If you actually need FlashAttention, you can install the wheel at https://github.com/kingbri1/flash-attention/releases

**Comment by SeanWang918** [comment]
tks! it works now !

**Comment by SIShanto** [comment]
> tks! it works now !

bro. how did it wirk? please enlighten me. I have cuda toolkit 12.9 and 5060ti 16 gb

**Comment by woct0rdho** [comment]
@SIShanto Do you see any error?

**Comment by SIShanto** [comment]
> [@SIShanto](https://github.com/SIShanto) Do you see any error?

Brother. It works fine. Just used pip code on the manual of PyTorch website. Runs completely fine. Sorry for late reply
