### ISSUE TITLE
Why is this happening? I can find my 5090D using comfyui, why can't this one?

### ISSUE THREAD

**Issue by kekekekekeshi** [lllyasviel/FramePack#691]
python demo_gradio.py
Currently enabled native sdp backends: ['flash', 'math', 'mem_efficient', 'cudnn']
Xformers is not installed!
Flash Attn is not installed!
Sage Attn is not installed!
/home/eashion/.pyenv/versions/framepack/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5090 D with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 D GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Namespace(share=False, server='0.0.0.0', port=None, inbrowser=False, output_dir='./outputs', fp32=False)
Free VRAM 5.11553955078125 GB
High-VRAM Mode: False
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 26.60it/s]
Fetching 3 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 5015.11it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  7.55it/s]
transformer.high_quality_fp32_output_for_inference = True
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.
Loaded CLIPTextModel to cuda:0 as complete.
Traceback (most recent call last):
  File "/home/eashion/FramePack/demo_gradio.py", line 141, in worker
    llama_vec, clip_l_pooler = encode_prompt_conds(prompt, text_encoder, text_encoder_2, tokenizer, tokenizer_2)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/framepack/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/FramePack/diffusers_helper/hunyuan.py", line 31, in encode_prompt_conds
    llama_attention_length = int(llama_attention_mask.sum())
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Unloaded CLIPTextModel as complete.
Unloaded DynamicSwap_LlamaModel as complete.
Unloaded CLIPTextModel as complete.
Unloaded SiglipVisionModel as complete.
Unloaded AutoencoderKLHunyuanVideo as complete.
Unloaded DynamicSwap_HunyuanVideoTransformer3DModelPacked as complete.

**Why is this happening? I can find my 5090D using comfyui, why can't this one?**

**Comment by kekekekekeshi** [comment]
<img width="676" alt="Image" src="https://github.com/user-attachments/assets/71a69736-c14b-404e-9ebe-584ea677f72b" />

**I'm sure there's nothing wrong with my 5090D**

python -c "import torch; print(torch.__version__)"
2.7.1+cu126

**Comment by kekekekekeshi** [comment]
[https://pytorch.org/get-started/locally/](url)
以我的配置为例：
先卸载：pip3 uninstall torch torchvision torchaudio 
在安装：
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
可以解决：
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.
但是又发生新的问题了

<img width="1740" alt="Image" src="https://github.com/user-attachments/assets/58524319-312e-4bca-8d43-002378527ee4" />

**Comment by kekekekekeshi** [comment]
哈哈哈哈哈哈哈哈。我已经搞定了。请叫我活雷锋！！！！！
